### ISSUE TITLE
テスト実行時にRuntime Errorが発生する

### ISSUE THREAD

**Issue by vlayusuke** [chaingng/shoeisha_serverless_python_tutorial#10]
一通りの実装を行なって。ローカル環境でテスト実行を試みると、以下のRuntime Errorが発生します。

```
RuntimeError
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.

Traceback (most recent call last)
File "/Users/vlayusuke/.local/share/virtualenvs/python-application-b-zDfMUK/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/vlayusuke/.local/share/virtualenvs/python-application-b-zDfMUK/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "/Users/vlayusuke/.local/share/virtualenvs/python-application-b-zDfMUK/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/vlayusuke/.local/share/virtualenvs/python-application-b-zDfMUK/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/Users/vlayusuke/.local/share/virtualenvs/python-application-b-zDfMUK/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/Users/vlayusuke/.local/share/virtualenvs/python-application-b-zDfMUK/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/vlayusuke/.local/share/virtualenvs/python-application-b-zDfMUK/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/Users/vlayusuke/.local/share/virtualenvs/python-application-b-zDfMUK/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/Users/vlayusuke/.local/share/virtualenvs/python-application-b-zDfMUK/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/vlayusuke/.local/share/virtualenvs/python-application-b-zDfMUK/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/vlayusuke/.local/share/virtualenvs/python-application-b-zDfMUK/lib/python3.8/site-packages/flask_login/utils.py", line 271, in decorated_view
return current_app.login_manager.unauthorized()
File "/Users/vlayusuke/.local/share/virtualenvs/python-application-b-zDfMUK/lib/python3.8/site-packages/flask_login/login_manager.py", line 165, in unauthorized
flash(self.login_message, category=self.login_message_category)
File "/Users/vlayusuke/.local/share/virtualenvs/python-application-b-zDfMUK/lib/python3.8/site-packages/flask/helpers.py", line 423, in flash
session["_flashes"] = flashes
File "/Users/vlayusuke/.local/share/virtualenvs/python-application-b-zDfMUK/lib/python3.8/site-packages/werkzeug/local.py", line 351, in __setitem__
self._get_current_object()[key] = value
File "/Users/vlayusuke/.local/share/virtualenvs/python-application-b-zDfMUK/lib/python3.8/site-packages/flask/sessions.py", line 102, in _fail
raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set. Set the secret_key on the application to something unique and secret.
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
```

原因としては、`views/entries.py`と`views/views.py`の中で、明示的にsessionをimportしているからなのではないかと考えているのですが、これを回避する方法がありましたらご教示いただければ幸いです。

参考:
[【Flask】Sessionについて](https://qiita.com/eee-lin/items/4e9a2a308ca52b58fd1e)

開発環境:
- macOS: 11.6
- python: 3.8.10
- Flask: 1.1.2

**Comment by chaingng** [comment]
@vlayusuke 
該当のエラーですが、configにて `SECRET_KEY` が見つからないため発生するエラーになります。

最初にセッションを利用しているのはログイン実装の章になりまして、こちらではじめてconfigに `SECRET_KEY`を設定しています。
まずは上記設定をご確認いただき、ローカルでのログインが正しく動作するか確認してみていただけますでしょうか。

**Comment by chaingng** [comment]
@vlayusuke　
個別にご共有いただいたコードにて上記方法で解決することが確認できましたので、本件closeとさせていただきます。
ありがとうございました。
