### ISSUE TITLE
ch. 8-9 動作を確認でImportError: cannot import name 'app' from partially initialized module 'flask_blog'

### ISSUE THREAD

**Issue by taiyodayo** [chaingng/shoeisha_serverless_python_tutorial#11]
Chapter 7までは順調に動作させられたのですが、Ch.8でつまづいています

打ち損じなど考慮し、すべてこちらのgitレポからのコピペに置き換えてみたりしたのですが、下記のエラーが出て次に進めません。

```
>python server.py
Traceback (most recent call last):
  File "server.py", line 1, in <module>
    from flask_blog import app
  File "/Users/taiyodayo/dev/shoeisha_diy/application/flask_blog/__init__.py", line 4, in <module>
    from flask_blog.views import views, entries
  File "/Users/taiyodayo/dev/shoeisha_diy/application/flask_blog/views/views.py", line 2, in <module>
    from flask_blog import app
ImportError: cannot import name 'app' from partially initialized module 'flask_blog' (most likely due to a circular import) (/Users/taiyodayo/dev/shoeisha_diy/application/flask_blog/__init__.py)
```
回帰読み込みに関するエラーが出ておりますが、
Flaskが初めてでここからどう対応するべきかわからずに居ます。
何かヒントがありまたらご教示頂けませんでしょうか。

環境: MacOS 12.0.1
python: minicondaで `conda create -n test python=3.8`
conda activate 内で `pip install pipenv`
Python 3.8.12 / pip 21.3.1

```pipenv
> pipenv graph
autopep8==1.6.0
  - pycodestyle [required: >=2.8.0, installed: 2.8.0]
  - toml [required: Any, installed: 0.10.2]
Flask-Login==0.5.0
  - Flask [required: Any, installed: 1.1.2]
    - click [required: >=5.1, installed: 8.0.3]
    - itsdangerous [required: >=0.24, installed: 2.0.1]
    - Jinja2 [required: >=2.10.1, installed: 3.0.3]
      - MarkupSafe [required: >=2.0, installed: 2.0.1]
    - Werkzeug [required: >=0.15, installed: 2.0.2]
Flask-Script==2.0.6
  - Flask [required: Any, installed: 1.1.2]
    - click [required: >=5.1, installed: 8.0.3]
    - itsdangerous [required: >=0.24, installed: 2.0.1]
    - Jinja2 [required: >=2.10.1, installed: 3.0.3]
      - MarkupSafe [required: >=2.0, installed: 2.0.1]
    - Werkzeug [required: >=0.15, installed: 2.0.2]
pynamodb==5.1.0
  - botocore [required: >=1.12.54, installed: 1.23.21]
    - jmespath [required: >=0.7.1,<1.0.0, installed: 0.10.0]
    - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.2]
      - six [required: >=1.5, installed: 1.16.0]
    - urllib3 [required: >=1.25.4,<1.27, installed: 1.26.7]
```

**Comment by taiyodayo** [comment]
すいません自己解決出来ました。

VSCodeのPEP8自動フォーマッターが作動した事が原因のようで、
これは import 関連の命令を、自動的にファイルの一番上に集める動作をします。

その際に `application/__init__.py` 内の import 文の順序が変わってしまい、
インポートエラーになっていたのが原因でした。

自動フォーマッタをオフにして、本書通りにファイルの中身を整理したところ動作するようになりました。
