### ISSUE TITLE
ch.9-6 デプロイ時にTemplateがadd_descriptionのattributeを無いエラー

### ISSUE THREAD

**Issue by shinriyo** [chaingng/shoeisha_serverless_python_tutorial#4]
P178の`zappa deploy dev`で発生しました。

```
AttributeError: 'Template' object has no attribute 'add_description'
```

ch.9-6 デプロイ時に502エラーとなる #1
のチケットとは別の現象です。

```
zappa deploy dev
Calling deploy for stage dev..
Creating application-dev-ZappaLambdaExecutionRole IAM Role..
Creating zappa-permissions policy on application-dev-ZappaLambdaExecutionRole IAM Role.
Downloading and installing dependencies..
 - pyyaml==5.4.1: Downloading
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 662k/662k [00:00<00:00, 15.9MB/s]
 - markupsafe==2.0.1: Downloading
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30.6k/30.6k [00:00<00:00, 5.97MB/s]
Packaging project as zip.
Uploading application-dev-1627053968.zip (45.3MiB)..
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 47.5M/47.5M [00:40<00:00, 1.16MB/s]
Scheduling..
Scheduled application-dev-zappa-keep-warm-handler.keep_warm_callback with expression rate(4 minutes)!
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/shinriyo/.local/share/virtualenvs/application-jAa1F8aU/lib/python3.8/site-packages/zappa/cli.py", line 3422, in handle
    sys.exit(cli.handle())
  File "/Users/shinriyo/.local/share/virtualenvs/application-jAa1F8aU/lib/python3.8/site-packages/zappa/cli.py", line 588, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/shinriyo/.local/share/virtualenvs/application-jAa1F8aU/lib/python3.8/site-packages/zappa/cli.py", line 630, in dispatch_command
    self.deploy(self.vargs["zip"], self.vargs["docker_image_uri"])
  File "/Users/shinriyo/.local/share/virtualenvs/application-jAa1F8aU/lib/python3.8/site-packages/zappa/cli.py", line 952, in deploy
    template = self.zappa.create_stack_template(
  File "/Users/shinriyo/.local/share/virtualenvs/application-jAa1F8aU/lib/python3.8/site-packages/zappa/core.py", line 2417, in create_stack_template
    self.cf_template.add_description("Automatically generated with Zappa")
AttributeError: 'Template' object has no attribute 'add_description'

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Zappa/Zappa
And join our Slack channel here: https://zappateam.slack.com
Love!,
 ~ Team Zappa!
```

**Comment by shinriyo** [comment]
zappaのバージョン違いなのかGitHub上の`Pipfile.lock`を真似して以下のを入れ直したが未解決でした。

```
pipenv install zappa==0.53.0
```

**Comment by shinriyo** [comment]
ZappaにIssueがあり
https://github.com/Miserlou/Zappa/issues/2225

そもそもインストールしてないがtroposphereのこのバージョンを入れても解決せず。
```
pipenv install troposphere==2.7.1
```

**Comment by shinriyo** [comment]
`0.53.0`ではなかったです。しかし以下でも未解決
```
pipenv install zappa==0.52.0 
```

**Comment by shinriyo** [comment]
一度上げた後にすでにあるので`update`するのが駄目みたいです。
つまり以下で行っていました。
```
zappa update dev
```


```
pipenv install zappa==0.52.0
pipenv install troposphere==2.7.1
```
をした後、
```
zappa undeploy dev
zappa deploy dev
```
で上げ直したら成功しました。

**Comment by shinriyo** [comment]
P195のzappaも同様にしたほうが良いですね。

**Comment by vlayusuke** [comment]
本件は、筆者のかたが[README.md](https://github.com/chaingng/shoeisha_serverless_python_tutorial/blob/master/README.md)の中で描いてくださっている通り、Zappaの互換性によるものの可能性が高いですね。

現在[Template: add_description -> set_description (stratosphere 3.x). #999](https://github.com/zappa/Zappa/pull/999)でプルリクエストがされているのですが、本線のバージョンがまだ0.3.0のままで、この修正が取り込まれたバージョン(0.3.2?)がリリースされていないため、リリースを待っているステータスです。

開発環境:
- MacBook Air (Retina, 13-inch, 2018)
- macOS Big Sur 11.6
- Python 3.8

**Comment by vlayusuke** [comment]
[Zappa0.54.0](https://github.com/zappa/Zappa/releases/tag/0.54.0)がリリースされていたので

`python3 -m pip install "zappa==0.54.0"`

でインストールを行い、

```
zappa undeploy dev
zappa deploy dev
```

で、デプロイを試行してみたのですが、やはり同じところでエラーが起きますね。

```
% zappa deploy dev
Important! A new version of Zappa is available!
Upgrade with: pip install zappa --upgrade
Visit the project page on GitHub to see the latest changes: https://github.com/Zappa/Zappa
Calling deploy for stage dev..
Creating zappa-permissions policy on python-app-dev-ZappaLambdaExecutionRole IAM Role.
Downloading and installing dependencies..
 - markupsafe==2.0.1: Downloading
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30.6k/30.6k [00:00<00:00, 6.99MB/s]
Packaging project as zip.
Uploading python-app-dev-1634245426.zip (44.8MiB)..
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 47.0M/47.0M [00:04<00:00, 10.3MB/s]
Scheduling..
Scheduled python-app-dev-zappa-keep-warm-handler.keep_warm_callback with expression rate(4 minutes)!
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/zappa/cli.py", line 3422, in handle
    sys.exit(cli.handle())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/zappa/cli.py", line 588, in handle
    self.dispatch_command(self.command, stage)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/zappa/cli.py", line 630, in dispatch_command
    self.deploy(self.vargs["zip"], self.vargs["docker_image_uri"])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/zappa/cli.py", line 952, in deploy
    template = self.zappa.create_stack_template(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/zappa/core.py", line 2417, in create_stack_template
    self.cf_template.add_description("Automatically generated with Zappa")
AttributeError: 'Template' object has no attribute 'add_description'

==============
```

ZappaのGitHub上でもissueを投げているのですが、まだ具体的な回答は得られていない状況です。

念の為、`pip list`した結果を貼り付けます。

```
python-app % pip list
Package             Version
------------------- ---------
argcomplete         1.12.3
boto3               1.18.62
botocore            1.21.62
certifi             2021.10.8
cfn-flip            1.3.0
charset-normalizer  2.0.7
click               8.0.3
durationpy          0.5
Flask               1.1.2
Flask-Login         0.5.0
Flask-Script        2.0.6
Flask-Sessionstore  0.4.5
future              0.18.2
hjson               3.0.2
idna                3.3
itsdangerous        2.0.1
Jinja2              3.0.2
jmespath            0.10.0
kappa               0.6.0
MarkupSafe          2.0.1
pep517              0.11.0
pip                 21.2.4
pip-tools           6.4.0
placebo             0.10.0
pynamodb            5.1.0
python-dateutil     2.8.2
python-slugify      5.0.2
PyYAML              6.0
requests            2.26.0
s3transfer          0.5.0
setuptools          58.1.0
six                 1.16.0
text-unidecode      1.3
toml                0.10.2
tomli               1.2.1
tqdm                4.62.3
troposphere         3.0.3
urllib3             1.26.7
Werkzeug            0.16.1
wheel               0.37.0
wsgi-request-logger 0.4.6
zappa               0.54.0
```

**Comment by chaingng** [comment]
@shinriyo 
コメントありがとうございます。
おっしゃるとおり、すでに一度deployしていた場合は以下の対応も必要でしたので補足ありがとうございます。

```
zappa undeploy dev
zappa deploy dev
```

[README](https://github.com/chaingng/shoeisha_serverless_python_tutorial/blob/master/README.md#3zappa-deploy%E5%AE%9F%E8%A1%8C%E6%99%82%E3%81%AB%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%8C%E7%99%BA%E7%94%9F%E3%81%99%E3%82%8B)に記載させていただきましたので、こちらはcloseさせていただきます。

@vlayusuke 
確認ありがとうございます。本家が対応されましたらREADMEの方も更新させていただきます。
