### ISSUE TITLE
ch05 ローカルDBの状態で「The security token included in the request is invalid.」になる

### ISSUE THREAD

**Issue by Satio-nozomi** [chaingng/shoeisha_serverless_python_tutorial#8]
p108 の
$ python manage.py init_db
を実行すると、セキュリティトークンが無効だと警告がでます。
正誤表のaccessを修正した上で実行しましたが、特に変わりないです
ローカルDBだと、AWSの認証不要だと記載ありましたが、この時点で必要でしょうか

- modeles/entries.py
```
from datetime import datetime
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute, NumberAttribute, UTCDateTimeAttribute
from flask_blog import app

class Entry(Model):
    class Meta:
        table_name = "serverless_blog_entries"
        region = app.config.get('DYNAMODB_REGION')
        aws_access_key_id = app.config.get('AWS_ACCESS_KEY_ID')
        aws_secret_access_key = app.config.get('AWS_SECRET_ACCESS_KEY')
        host = app.config.get('DYNAMODB_ENDPOINT_URL')
    id = NumberAttribute(hash_key=True, null=False)
    title = UnicodeAttribute(null=True)
    text = UnicodeAttribute(null=True)
    created_at = UTCDateTimeAttribute(default=datetime.now)
```

- config.py
```
DEBUG = True
DYNAMODB_REGION = 'ap-northeast-1'
AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID'
AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY'
DYNAMODB_ENDOPOINT_URL = 'http://localhost:8000'


```

- エラーメッセージ
```
(apli) (base) saitonozomi@saitounozomunoiMac [14時17分46秒] [~/apli] 
-> % python manage.py init_db
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    manager.run()
  File "/Users/saitonozomi/.local/share/virtualenvs/apli-XhvBMDBA/lib/python3.8/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/Users/saitonozomi/.local/share/virtualenvs/apli-XhvBMDBA/lib/python3.8/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/Users/saitonozomi/.local/share/virtualenvs/apli-XhvBMDBA/lib/python3.8/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/Users/saitonozomi/apli/flask_blog/scripts/db.py", line 8, in run
    if not Entry.exists():
  File "/Users/saitonozomi/.local/share/virtualenvs/apli-XhvBMDBA/lib/python3.8/site-packages/pynamodb/models.py", line 753, in exists
    cls._get_connection().describe_table()
  File "/Users/saitonozomi/.local/share/virtualenvs/apli-XhvBMDBA/lib/python3.8/site-packages/pynamodb/connection/table.py", line 290, in describe_table
    return self.connection.describe_table(self.table_name)
  File "/Users/saitonozomi/.local/share/virtualenvs/apli-XhvBMDBA/lib/python3.8/site-packages/pynamodb/connection/base.py", line 748, in describe_table
    tbl = self.get_meta_table(table_name, refresh=True)
  File "/Users/saitonozomi/.local/share/virtualenvs/apli-XhvBMDBA/lib/python3.8/site-packages/pynamodb/connection/base.py", line 548, in get_meta_table
    data = self.dispatch(DESCRIBE_TABLE, operation_kwargs)
  File "/Users/saitonozomi/.local/share/virtualenvs/apli-XhvBMDBA/lib/python3.8/site-packages/pynamodb/connection/base.py", line 329, in dispatch
    data = self._make_api_call(operation_name, operation_kwargs, settings)
  File "/Users/saitonozomi/.local/share/virtualenvs/apli-XhvBMDBA/lib/python3.8/site-packages/pynamodb/connection/base.py", line 440, in _make_api_call
    raise VerboseClientError(botocore_expected_format, operation_name, verbose_properties)
pynamodb.exceptions.VerboseClientError: An error occurred (UnrecognizedClientException) on request (R6JVC7KO8N2EEPUR65VRHUS8G3VV4KQNSO5AEMVJF66Q9ASUAAJG) on table (serverless_blog_entries) when calling the DescribeTable operation: The security token included in the request is invalid.
```

**Comment by Satio-nozomi** [comment]
すみません
DYNAMODB_ENDOPOINT_URL
のタイポが原因みたいでした。
